In [75]:
import numpy as np
import math

In [ ]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [ ]:
(a < 0).sum()


2. How many positive numbers are there?

In [ ]:
(a > 0).sum()

3. How many even positive numbers are there?

In [ ]:
np.sum((a > 0) & (a % 2 == 0))


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [ ]:
((a + 3) > 0).sum()

5. If you squared each number, what would the new mean and standard deviation be?

In [ ]:
(a ** 2).mean()

In [ ]:
(a ** 2).std()

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.



In [ ]:
a.mean()
#create function to center data
center_function = lambda x: x - x.mean()

#apply function to original NumPy array
data_centered = center_function(a)

#view updated Array
data_centered



In [ ]:
#Another way:
import statistics as st
list_average = st.mean(a)
centered = a - list_average
centered




7. Calculate the z-score for each data point. Recall that the z-score is given by:


In [ ]:
# Calculate the z-score from with scipy using sample population
import scipy.stats as stats

zscores = stats.zscore(a)
print(a.std())
print(a)
print(zscores)


In [ ]:
#Another Z-Score solution
# Zscore = (observed value (a) - mean ) / std()
import statistics as st
print(a)
(a - a.mean()) / st.stdev(a)

In [24]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

## 1
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [4]:
sum_of_a = a.sum()


In [ ]:
min_of_a = a.min()

In [ ]:
max_of_a = a.max()

In [ ]:
mean_of_a = a.mean()

In [25]:
squares_of_a = a ** 2

squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
def find_product(arr, size):
    result = 1
    for i in range(size):
        result = result * arr[i]
    return result

size1 = len(a)
find_product(a, size1)

3628800

In [26]:
a.prod()

3628800

In [17]:
odds_in_a = a % 2 == 1

In [18]:
a[odds_in_a]

array([1, 3, 5, 7, 9])

In [19]:
evens_in_a = a % 2 == 0
a[evens_in_a]

array([ 2,  4,  6,  8, 10])

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

#Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


#Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

#Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


#Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


#Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

#Exercise 9 - print out the shape of the array b.

#Exercise 10 - transpose the array b.

#Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [8]:
b = np.array([[3, 4, 5], 
             [6, 7, 8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [16]:
b.sum()
#sum_of_b = 0
#for row in b:
#    sum_of_b += sum(row)

33

In [47]:
b.min()
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

3

In [18]:
b.max()
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

8

In [20]:
b.mean()
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b

5.5

In [27]:
b.prod()
#product_of_b = 1 
#for row in b: 
#    for number in row: 
#        product_of_b *= number

product_of_b

20160

In [28]:
squares_of_b = b ** 2
#squares_of_b = [] 
#for row in b: 
#    for number in row: 
#        squares_of_b.append(number**2)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [29]:
odds_in_b = b % 2 == 1
#odds_in_b = [] 
#for row in b: 
#    for number in row: 
#        if(number % 2 != 0): 
#            odds_in_b.append(number)
b[odds_in_b]

array([3, 5, 7])

In [31]:
evens_in_b = b % 2 == 0
#evens_in_b = [] 
#for row in b: 
#    for number in row: 
#        if(number % 2 == 0): 
#            evens_in_b.append(number)

b[evens_in_b]

array([4, 6, 8])

In [32]:
b.shape

(2, 3)

In [33]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [35]:
b[0:]

array([[3, 4, 5],
       [6, 7, 8]])

In [41]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [42]:
b.reshape((6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

 HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
 
#Exercise 1 - Find the min, max, sum, and product of c.

#Exercise 2 - Determine the standard deviation of c.

#Exercise 3 - Determine the variance of c.

#Exercise 4 - Print out the shape of the array c

#Exercise 5 - Transpose c and print out transposed result.

#Exercise 6 - Get the dot product of the array c with c. 

#Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

#Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [63]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
c.min()

1

In [49]:
c.max()

9

In [50]:
c.sum()

45

In [51]:
c.prod()

362880

In [52]:
c.std()

2.581988897471611

In [54]:
c.var()

6.666666666666667

In [55]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
c.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [65]:
c = c * c.transpose()

In [67]:
c.sum()

261

In [68]:
c.prod()

131681894400

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

#Exercise 1 - Find the sine of all the numbers in d

#Exercise 2 - Find the cosine of all the numbers in d

#Exercise 3 - Find the tangent of all the numbers in d

#Exercise 4 - Find all the negative numbers in d

#Exercise 5 - Find all the positive numbers in d

#Exercise 6 - Return an array of only the unique numbers in d.

#Exercise 7 - Determine how many unique numbers there are in d.

#Exercise 8 - Print out the shape of d.

#Exercise 9 - Transpose and then print out the shape of d.

#Exercise 10 - Reshape d into an array of 9 x 2

In [80]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [82]:
sin_values = np.sin(d)
sin_values

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [83]:
cos_values = np.cos(d)
cos_values

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [84]:
tan_values = np.tan(d)
tan_values

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [86]:
negatives_in_d = d < 0
d[negatives_in_d]

array([-90, -30, -45, -45])

In [87]:
positives_in_d = d > 0
d[positives_in_d]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [93]:
unique_values = np.unique(d)
unique_values

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [103]:
unique, frequency = np.unique(d, return_counts = True) 
  
# convert both into one numpy array
count = np.asarray((unique, frequency ))
how_many = 0
count


array([[-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270],
       [  1,   2,   1,   2,   1,   3,   1,   3,   1,   2,   1]])

In [105]:
d.shape

(3, 6)

In [107]:
d = d.transpose()
d

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [109]:
d.reshape((9, 2))

array([[ 90,  45],
       [ 60,  30],
       [-90,  45],
       [ 45, -30],
       [-45,   0],
       [270,  90],
       [120,  90],
       [-45, 180],
       [  0, 180]])